-- RBAC v2: additional role management

ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SUPERADMIN';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SYSADMIN';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'DIRECTOR';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'COLABORADOR';
